# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sanshi Lei Yu's Homepage
email: meet.leiyu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sanshi Lei Yu's Homepage.
twitter_username: yusanshi
github_username: yusanshi
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
# Outputting
permalink: /posts/:title/
paginate: 5 # amount of posts to show
paginate_path: /posts/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Sanshi Lei Yu"
  avatar: "/assets/images/portrait.jpg"
  bio: "Postgraduate, CS, USTC"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:meet.leiyu@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yusanshi"
    # - label: "LinkedIn"
    #   icon: "fab fa-fw fa-linkedin" # TODO icon color?
    #   url: "https://www.linkedin.com/in/yusanshi/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=dE3GoNsAAAAJ"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Sanshi-Lei-Yu"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0001-9393-1397"

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/yusanshi"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      show_date: true
      toc: true
      toc_label: "Table of Contents"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

tag_archive:
  type: liquid
  path: /tags/

github: [metadata]

comments:
  provider: "disqus"
  disqus:
    shortname: "yusanshi"

atom_feed:
  hide: true
