# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sanshi Lei Yu's Homepage
email: meet.leiyu@gmail.com
description: Sanshi Lei Yu's Homepage.
minimal_mistakes_skin: default

search: true
search_full_content: true
search_provider: 'lunr'
lunr:
  search_within_pages: true

# Build settings
markdown: kramdown
remote_theme: 'mmistakes/minimal-mistakes@8a67ce8e41ec850f2d7c373aa47739b2abfee6f1' # 2022.7.14
# Outputting
permalink: /posts/:year-:month-:day/:slug/
paginate: 5 # amount of posts to show
paginate_path: /posts/:num/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

analytics:
  provider: 'custom'

author:
  name: 'Sanshi Lei Yu'
  avatar: '/assets/images/portrait.jpg'
  bio: 'Postgraduate, CS, USTC'
  links:
    - label: 'Email'
      icon: 'fas fa-fw fa-envelope'
      url: 'mailto:meet.leiyu@gmail.com'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/yusanshi'
    # - label: "LinkedIn"
    #   icon: "fab fa-fw fa-linkedin" # TODO icon color?
    #   url: "https://www.linkedin.com/in/yusanshi/"
    - label: 'Google Scholar'
      icon: 'fas fa-fw fa-graduation-cap'
      url: 'https://scholar.google.com/citations?user=dE3GoNsAAAAJ'
    - label: 'ResearchGate'
      icon: 'fab fa-fw fa-researchgate'
      url: 'https://www.researchgate.net/profile/Sanshi-Lei-Yu'
    - label: 'ORCID'
      icon: 'fab fa-fw fa-orcid'
      url: 'https://orcid.org/0000-0001-9393-1397'

defaults:
  # _posts
  - scope:
      path: '_posts'
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 160
      comments: true
      show_date: true
      toc: true
      toc_label: 'Table of Contents'
      toc_sticky: true
  # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: single-no-heading
      author_profile: true

tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: 'disqus'
  disqus:
    shortname: 'yusanshi'

atom_feed:
  hide: true

beian: '豫ICP备17024561号'

cookie_consent: true
